# Generated by Django 2.1.5 on 2020-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rolepermissionsmanagerlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('rolename', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('documentid', models.IntegerField(blank=True, null=True)),
                ('documentname', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.IntegerField()),
                ('write', models.IntegerField()),
                ('create', models.IntegerField()),
                ('delete', models.IntegerField()),
                ('print', models.IntegerField()),
                ('email', models.IntegerField()),
                ('report', models.IntegerField()),
                ('imports', models.IntegerField()),
                ('exports', models.IntegerField()),
                ('share', models.IntegerField()),
                ('others', models.IntegerField()),
            ],
            options={
                'db_table': 'view_rolepermissionsmanager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('menuId', models.IntegerField(blank=True, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('access_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('access', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=60, unique=True)),
                ('type', models.IntegerField(default=1)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(default=0, null=True)),
                ('modifiedon', models.DateTimeField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('appsettings_access', models.IntegerField(default=0)),
                ('appsettings_create', models.IntegerField(default=0)),
                ('appsettings_edit', models.IntegerField(default=0)),
                ('appsettings_delete', models.IntegerField(default=0)),
                ('profiles_access', models.IntegerField(default=0)),
                ('profiles_create', models.IntegerField(default=0)),
                ('profiles_edit', models.IntegerField(default=0)),
                ('profiles_delete', models.IntegerField(default=0)),
                ('users_access', models.IntegerField(default=0)),
                ('users_create', models.IntegerField(default=0)),
                ('users_edit', models.IntegerField(default=0)),
                ('users_delete', models.IntegerField(default=0)),
                ('company_access', models.IntegerField(default=0)),
                ('company_create', models.IntegerField(default=0)),
                ('company_edit', models.IntegerField(default=0)),
                ('company_delete', models.IntegerField(default=0)),
                ('screensettings_access', models.IntegerField(default=0)),
                ('screensettings_create', models.IntegerField(default=0)),
                ('screensettings_edit', models.IntegerField(default=0)),
                ('screensettings_delete', models.IntegerField(default=0)),
                ('managepermissions_access', models.IntegerField(default=0)),
                ('managepermissions_create', models.IntegerField(default=0)),
                ('managepermissions_edit', models.IntegerField(default=0)),
                ('managepermissions_delete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rolepermissionsmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('documentid', models.IntegerField(blank=True, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.IntegerField()),
                ('write', models.IntegerField()),
                ('create', models.IntegerField()),
                ('delete', models.IntegerField()),
                ('print', models.IntegerField()),
                ('email', models.IntegerField()),
                ('report', models.IntegerField()),
                ('imports', models.IntegerField()),
                ('exports', models.IntegerField()),
                ('share', models.IntegerField()),
                ('others', models.IntegerField()),
            ],
        ),
    ]
