# Generated by Django 3.0.6 on 2020-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfilePermissions',
        ),
        migrations.DeleteModel(
            name='rolepermissionsmanager',
        ),
        migrations.DeleteModel(
            name='rolepermissionsmanagerlist',
        ),
    ]
