# Generated by Django 3.0.6 on 2020-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_stlicings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_stlicings', models.IntegerField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Agent_stlicings',
            },
        ),
        migrations.CreateModel(
            name='User_cable_connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('caf_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'User_cable_connections',
            },
        ),
    ]
