# Generated by Django 3.0.6 on 2020-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200521_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
