# Generated by Django 3.0.6 on 2020-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200521_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
