# Generated by Django 3.0.6 on 2020-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200523_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
