# Generated by Django 3.0.6 on 2020-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_reports_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
