# Generated by Django 3.0.6 on 2021-03-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20201119_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
