# Generated by Django 3.0.6 on 2021-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Time',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
