# Generated by Django 3.0.6 on 2021-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
