# Generated by Django 3.0.6 on 2020-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CAF_NO', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('AADHAR_NO', models.CharField(blank=True, max_length=255, null=True)),
                ('Box_no', models.CharField(blank=True, max_length=255, null=True)),
                ('Activation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
