# Generated by Django 2.1.5 on 2020-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('profile', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('username', models.CharField(max_length=60)),
                ('profilename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'view_userslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('cemail', models.CharField(blank=True, max_length=200, null=True)),
                ('caddress', models.CharField(blank=True, max_length=200, null=True)),
                ('cphone', models.CharField(blank=True, max_length=15, null=True)),
                ('gst', models.CharField(blank=True, max_length=100, null=True)),
                ('supassword', models.CharField(blank=True, max_length=255, null=True)),
                ('dbname', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(upload_to='company/')),
                ('invoicelogo', models.FileField(upload_to='company/')),
                ('createdby', models.IntegerField(default=0, null=True)),
                ('modifiedby', models.IntegerField(default=0, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('modifiedon', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('profile', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(default=1, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='users/')),
                ('login', models.CharField(default='0', max_length=1, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(default=0, null=True)),
                ('modifiedon', models.DateTimeField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
