# Generated by Django 3.0.6 on 2020-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('profile', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(default=1, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='users/')),
                ('login', models.CharField(default='0', max_length=1, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(default=0, null=True)),
                ('modifiedon', models.DateTimeField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Userslist',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='supassword',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='cphone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='caddress',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='cemail',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='dbname',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='invoicelogo',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='logo',
        ),
        migrations.AddField(
            model_name='companys',
            name='gender',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='googlepe',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companys',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companys',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='password',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='phonepe',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companys',
            name='profile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='username',
            field=models.CharField(default='null', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companys',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
