# Generated by Django 3.0.6 on 2020-05-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20200515_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='email',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='profile',
            new_name='agent_id',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='image',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='login',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='modifiedby',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='modifiedon',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='type',
        ),
    ]
