# Generated by Django 3.0.6 on 2020-05-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20200521_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companys',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='googlepe',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='modifiedby',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='modifiedon',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='phonepe',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='status',
        ),
    ]
