# Generated by Django 3.0.6 on 2020-05-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20200527_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companys',
            name='image',
        ),
    ]
