# Generated by Django 3.0.6 on 2020-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_remove_companys_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
