# Generated by Django 3.0.6 on 2020-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_auto_20200609_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
