# Generated by Django 3.0.6 on 2020-11-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_companys_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='companys',
            options={'verbose_name_plural': 'Companys'},
        ),
    ]
