# Generated by Django 3.0.6 on 2020-05-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cablebill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CAF_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.CharField(blank=True, max_length=255, null=True)),
                ('Box_number', models.CharField(blank=True, max_length=255, null=True)),
                ('OLT', models.CharField(blank=True, max_length=255, null=True)),
                ('PON', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.CharField(blank=True, max_length=255, null=True)),
                ('Lien_men', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
