# Generated by Django 3.0.6 on 2020-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CAF_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('Activation_Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Billing_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('OLT', models.CharField(blank=True, max_length=255, null=True)),
                ('PON', models.CharField(blank=True, max_length=255, null=True)),
                ('Box_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Balance_till_last_month', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.CharField(blank=True, max_length=255, null=True)),
                ('Lien_men', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('total_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('CAF_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Base_Package', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Billing_Frequency', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
