# Generated by Django 3.0.6 on 2020-05-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0002_bills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cablebill',
        ),
    ]
