# Generated by Django 3.0.6 on 2020-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0003_delete_cablebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
