# Generated by Django 3.0.6 on 2020-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0004_bills_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='Date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
