# Generated by Django 3.0.6 on 2020-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0005_auto_20200523_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
