# Generated by Django 3.0.6 on 2020-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0006_auto_20200526_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='Date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
