# Generated by Django 3.0.6 on 2020-11-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0009_bills_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name_plural': 'Bills'},
        ),
    ]
