# Generated by Django 3.0.6 on 2021-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0010_auto_20201119_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='Time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
